# Generated by Django 5.2.7 on 2025-10-17 22:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Costo en USD')),
                ('selling_price_local', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Venta Local')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('supplier_country', models.CharField(max_length=2, verbose_name='País del Proveedor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price_local', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_rate_used', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='books.book')),
            ],
            options={
                'verbose_name': 'Historial de Precios',
                'verbose_name_plural': 'Historial de Precios',
                'ordering': ['-created_at'],
            },
        ),
    ]
