# Generated by Django 5.2.7 on 2025-10-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='local_currency',
            field=models.CharField(default='MXN', max_length=3, verbose_name='Moneda Local'),
        ),
    ]
