# Generated by Django 5.2.7 on 2025-10-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_local_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='local_currency',
            field=models.CharField(default='VES', max_length=3, verbose_name='Moneda Local'),
        ),
    ]
